# Generated by Django 2.2.4 on 2019-09-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '패스트캠퍼스 태그', 'verbose_name_plural': '패스트캠퍼스 태그'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='fastcampus_tag',
        ),
    ]
