# Generated by Django 2.2.4 on 2019-08-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20190825_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='usermail',
            new_name='useremail',
        ),
    ]
